//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolcad23.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toolcad23.Localization.Gui", typeof(Gui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by: .
        /// </summary>
        internal static string InfoPage_PoweredBy {
            get {
                return ResourceManager.GetString("InfoPage.PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver.
        /// </summary>
        internal static string MainPage_Deliver {
            get {
                return ResourceManager.GetString("MainPage.Deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string MainPage_Lobby {
            get {
                return ResourceManager.GetString("MainPage.Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string MainPage_Retrieve {
            get {
                return ResourceManager.GetString("MainPage.Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue amount.
        /// </summary>
        internal static string RightPanel_BlueAmount {
            get {
                return ResourceManager.GetString("RightPanel.BlueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX on green.
        /// </summary>
        internal static string RightPanel_MaxGreen {
            get {
                return ResourceManager.GetString("RightPanel.MaxGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX on red.
        /// </summary>
        internal static string RightPanel_MaxRed {
            get {
                return ResourceManager.GetString("RightPanel.MaxRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string RightPanel_Randomize {
            get {
                return ResourceManager.GetString("RightPanel.Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White amount.
        /// </summary>
        internal static string RightPanel_WhiteAmount {
            get {
                return ResourceManager.GetString("RightPanel.WhiteAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow amount.
        /// </summary>
        internal static string RightPanel_YellowAmount {
            get {
                return ResourceManager.GetString("RightPanel.YellowAmount", resourceCulture);
            }
        }
    }
}
